openapi: 3.0.3
info:
  title: quarkus-final
  description: |-
    final test
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-example.com/rest/quarkus-final/0.0.1"
paths: {}
